name: Testing
on: [push, pull_request]
jobs:

  build:
    name: Testing
    runs-on: ubuntu-16.04
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2